# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Jinse Kim
baseurl:        ""
url:            "https://www.instagram.com/zzin_blue/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jinse Kim
  url:          "https://www.instagram.com/zzin_blue/"
  email:        justin1105kr@gmail.com  
  github:       dancingowl
  twitter:      Nan

# Custom vars
version:        0.0.1
github:
  repo:         https://github.com/dancingowl/dancingowl.github.io