# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Jihye Leee
baseurl:        ""
url:            "http://www.jihyeleee.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jinse Kim
  url:          http://jinsekim.com
  email:        justin1105kr@gmail.com  
  github:       dancingowl
  twitter:      Nan

# Custom vars
version:        0.0.1
github:
  repo:         https://github.com/dancingowl/dancingowl.github.io